config/routes.rb
WrapSemantic::Application.routes.draw do
  root "info#home"

  get "/sell-semantic-ui-themes", to: "info#sell", as: "sell"
  get "/logout",                  to: "sessions#destroy", as: "logout"
  get "/signin",                  to: "sessions#new",     as: "signin"
  get "/privacy-policy",          to: "info#privacy_policy"
  get "/terms",                   to: "info#terms"
  get "/faq",                     to: "info#faq"
  get "/about",                   to: "info#about"

  ["semantic-ui-themes", "semantic-ui-snippets"].each do |slug|
    controller = slug.gsub("semantic-ui-", "")
    get "/#{slug}", to: "#{controller}#index"
  end

  resource  :account,             only: [:show]
  resources :categories
  resource  :dashboard,           only: [:show]
  resources :downloads,           only: [:create]
  resources :expos,               except: [:show]

  resources :favorites,           only: [:create, :destroy]

  resources :payment_preferences, only: [:new, :create]
  resources :previews,            only: [:show]
  resources :sessions,            only: [:new, :create]
  resources :snippets do
    member do
      get 'iframe_content'
    end
  end
  resources :subscriptions,       only: [:create]

  resources :tags,                only: [:show]
  resources :themes, defaults: { format: "html" } do
    member do
      get 'preview'
    end
  end

  resources :theme_approvals,     only: [:update, :destroy]
  resources :expo_approvals,      only: [:update, :destroy]
  resources :users

  namespace :admin do
    resource :dashboard,          only: [:show]
  end
end

app/models/theme.rb
class Theme < ActiveRecord::Base
  PREPROCESSOR_OPTIONS = [ ["Select", nil], ["SASS", "SASS"],
                           ["LESS", "LESS"], ["Stylus", "Stylus"],
                           ["None", "None"]
                         ]
  BROWSER_OPTIONS      = [ "Chrome", "Safari", "Firefox", "IE10", "IE9", "IE8", "IE7" ]

  has_many :downloads

  has_many :theme_categories
  has_many :categories, through: :theme_categories

  has_many :taggings
  has_many :tags, through: :taggings

  has_many :favorites, as: :favorited, dependent: :destroy

  has_one :owner,      dependent: :destroy
  has_one :price_list, dependent: :destroy
  has_one :sales_tracker, dependent: :destroy

  has_many :subscriptions
  has_many :guest_subscriptions

  accepts_nested_attributes_for :price_list

  mount_uploader :image, ImageUploader
  mount_uploader :file_package, FilePackageUploader

  validates :name, :description, :preview_url, :file_package, :image, presence: true

  scope :approved,    -> { where(approved: true) }
  scope :pending,     -> { where(approved: false) }

  delegate :sale_count, :single_tier_count, :multiple_tier_count,
           :extended_tier_count, :revenue, :gross_sales,
       to: :sales_tracker


  def default_image_url
    if image_url.present?
      image_url
    else
      "https://s3.amazonaws.com/wrapsemanticstatic/placeholder.png"
    end
  end

  def tag_list
    tags.map(&:name).join(", ")
  end

  def tag_list=(tag_names)
    self.tags = tag_names.split(",").map do |n|
      Tag.where(name: n.strip).first_or_create!
    end
  end

  def approve!
    update_attribute(:approved, true)
  end

  def disapprove!
    update_attribute(:approved, false)
  end

  def to_param
    "#{id} #{name}".parameterize
  end

  def has_required_elements?
    # don't know what all to put in here right now
    price_list.present? && file_package.present?
  end

  def status
    approved? ? "Approved" : "Pending"
  end

  def current_price_list
    price_list || build_price_list
  end
end

app/controllers/themes_controller.rb
class ThemesController < ApplicationController
  before_filter :authenticate, only: [:new, :create, :destroy, :update, :edit]
  before_filter :get_theme, only: [:show, :edit, :update, :destroy, :preview ]

  def new
    @theme = Theme.new
  end

  def create
    @theme = Theme.new(theme_params)
    if @theme.save
      @theme.create_sales_tracker
      @theme.create_owner(user_id: current_user.id)
      redirect_to theme_path(@theme)
    else
      render :new
    end
  end

  def edit
    authorize(@theme)
  end

  def update
    authorize(@theme)
    if @theme.update_attributes(theme_params)
      redirect_to theme_path(@theme), notice: t(:"themes.updated")
    else
      render :edit
    end
  end

  def index
    @themes = Theme.approved.order('created_at desc').paginate(page: params[:page], per_page: 20)
  end

  def show
    @license = params[:license] || "single"
    if should_see_download_notice?
      flash[:notice] = t(:"downloads.reminder", name: @theme.name)
    end
  end

  def destroy
    authorize(@theme)
    @theme.destroy
    redirect_to themes_path, notice: 'Deletion successful'
  end

  def preview
    render layout: false
  end

  private
    def get_theme
      @theme = Theme.find(params[:id])
    end

    def authorize(theme)
      if !current_user.can_edit_theme?(theme)
        redirect_to themes_path
      end
    end

    def theme_params
      params.require(:theme).permit(:name, :description, :preview_url, :category_ids, { category_ids: [] },
                                    :image, :file_package, :tag_list, :preprocessor, { browsers: [] },
                                    price_list_attributes: [:single_tier, :multiple_tier, :extended_tier])
    end

    def should_see_download_notice?
      return if !params[:purchase_mailer]
      # Sometimes people are logged in AND somehow getting to the theme with a token
      # this forces the lookup on GuestSubscription if params[:token] exists
      if current_user && !params[:token]
        current_user.can_download?(@theme) || current_user.owns_theme?(@theme)
      elsif GuestSubscription.exists_and_downloadable?(params[:id], params[:token])
        true
      end
    end
end

app/helpers/themes_helper.rb
module ThemesHelper
  def theme_price_in_cents(price_list, license)
    case license
    when "single"
      price = price_list.single_tier
    when "multiple"
      price = price_list.multiple_tier
    when "extended"
      price = price_list.extended_tier
    end

    price.to_i * 100
  end

  def call_to_action(theme)
    # Sometimes people are logged in AND somehow getting to the theme with a token
    # this forces the lookup on GuestSubscription if params[:token] exists
    if current_user && !params[:token]
      if current_user.admin? && !theme.approved?
        render "approve_button"
      elsif current_user.can_download?(theme) || current_user.owns_theme?(theme)
        render "download_button"
      else
        render "subscriptions/button"
      end
    elsif GuestSubscription.exists_and_downloadable?(params[:id], params[:token])
      render "download_button"
    else
      render "subscriptions/button"
    end
  end

  def paypal_url
    if Rails.env.production?
      ENV["paypal_url"]
    else
      APP_CONFIG["paypal"]["url"]
    end
  end

end

app/views/themes/_approve_button.html.erb
<%= button_to theme_approval_path, class: "ui huge blue labeled icon fluid button", method: :put do %>
  Approve
  <i class="checkmark icon"></i>
<% end %>

app/views/themes/_download_button.html.erb
<% if params[:token] %>
  <%= button_to downloads_path(theme_id: @theme.id, token: params[:token]), class: "ui huge green labeled icon fluid button" do %>
    Download
    <i class="download icon"></i>
  <% end %>
<% else %>
  <%= button_to downloads_path(theme_id: @theme.id), class: "ui huge green labeled icon fluid button" do %>
    Download
    <i class="download icon"></i>
  <% end %>
<% end %>

app/views/themes/_form.html.erb
<%= form_for @theme do |f| %>

  <% if @theme.errors.any? %>
    <div class="ui red message">
      <div class="header">We noticed some issues</div>
      <ul class="list">
        <% @theme.errors.full_messages.each do |message| %>
          <li id="error"><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="ui form">
    <h3 class="ui header gr">Basics</h3>
    <div class="field">
      <%= f.label :name, "Theme Name" %>
      <%= f.text_field :name %>
    </div>
    <div class="field">
      <%= f.label :description, "Description (HTML allowed)" %>
      <%= f.text_area :description, :placeholder => "Info including pages, credits, features, etc." %>
    </div>
    <div class="field">
      <%= f.label :preview_url %>
      <%= f.url_field :preview_url, placeholder: "http://www.example.com/preview" %>
    </div>

    <div class="two fields">
      <div class="field">
        <%= f.label :image, "Preview Image" %>
        <%= f.file_field :image, :class => "image-arena" %>
      </div>

      <div class="field">
        <%= f.label :file_package %>
        <%= f.file_field :file_package, :class => "image-arena" %>
      </div>
    </div>

    <div class="two fields">
      <div class="field">
        <%= f.label :preprocessors %>
        <%= f.select :preprocessor, options_for_select(Theme::PREPROCESSOR_OPTIONS, f) %>
      </div>
      <div class="field">
        <%= f.label :category %>
        <%= collection_select(:theme, :category_ids, Category.all, :id, :name) %>
      </div>
    </div>
    <div class="field">
      <%= f.label :browsers, "Browser Support" %>
      <% Theme::BROWSER_OPTIONS.each do |browser| %>
        <div clas="ui checkbox">
          <%= check_box_tag 'theme[browsers][]', browser, @theme.browsers.include?(browser) %>
          <label for="<%= browser %>"><%= browser %></label>
        </div>
      <% end %>
    </div>
  </div>

  <%= f.fields_for :price_list, @theme.current_price_list do |p| %>
    <div class="ui form">
      <h3 class="ui header">Price</h3>
      <div class="inline field left icon input ui">
        <%= p.number_field :single_tier, :placeholder => "Single Application" %>
        <i class="dollar icon"></i>
<!--         <div class="ui pointing black left label">
          Single Application - $5 minimum <a href="#"> <i class="question circular icon"></i></a>
        </div> -->
      </div>
      <div class="inline field left icon input ui">
        <%= p.number_field :multiple_tier, :placeholder => "Multiple Applications" %>
        <i class="dollar icon"></i>
<!--         <div class="ui pointing black left label">
          Suggested: Single price x 3 <a href="#"> <i class="question circular icon"></i></a>
        </div> -->
      </div>
      <div class="inline field left icon input ui">
        <%= p.number_field :extended_tier, :placeholder => "Extended Application" %>
        <i class="dollar icon"></i>
<!--         <div class="ui pointing black left label">
          Suggested: Single price x 40 <a href="#"> <i class="question circular icon"></i></a>
        </div> -->
      </div>
    </div>
  <% end %>

  <div class="ui form">

    <h3 class="ui header gr">Add tags</h3>
    <div class="field">
      <%= f.label :tag_list, "Tags (Limit to 10)" %>
      <%= f.text_field :tag_list %>
    </div>

    <%= f.submit "Submit", :class => "ui button green" %>
  </div>
<% end %>

app/views/themes/_paypal_buy_form.html.erb
<form name="_xclick" action="<%= paypal_url %>" method="post" target="_blank">
  <input type="hidden" name="cmd" value="_xclick">
  <input type="hidden" name="business" value="purchases@semantickit.com">
  <input type="hidden" name="currency_code" value="USD">
  <input type="hidden" name="quantity" value="1">
  <input type="hidden" name="item_name" value="<%= @theme.name %>">
  <input type="hidden" name="amount" value="<%= @theme.price_list.send("#{@license}_tier") %>">

  <% if logged_in? %>
    <input type="hidden" name="notify_url" value="<%= subscriptions_url(id: @theme.id, price: @theme.price_list.send("#{@license}_tier"), count: "#{@license}_tier_count", paypal: true, user_id: current_user.id) %>">
  <% else %>
    <input type="hidden" name="notify_url" value="<%= subscriptions_url(id: @theme.id, price: @theme.price_list.send("#{@license}_tier"), count: "#{@license}_tier_count", paypal: true, logged_out: "true", guest_token: GuestSubscription.random_token) %>">
  <% end %>

  <span class="ui huge green animated fade labeled fluid button buy-button">
    <div class="visible content">
      <i class="tags icon"></i>
      buy now <%= number_to_currency(@theme.price_list.send("#{@license}_tier"), precision: 0) %>
    </div>
    <div class="hidden content">
      checkout with paypal
    </div>
    <input type="image" src="https://www.paypalobjects.com/webstatic/en_US/btn/btn_buynow_pp_142x27.png" border="0" name="submit" alt="Make payments with PayPal - it's fast, free and secure!" style="opacity:0; position: absolute; top: 0; left: 0; width: 100%; height: 100%;">
  </span>
</form>

app/views/themes/edit.html.erb
<% content_for :title do %>
  Edit Your Theme
<% end %>
<% content_for :subtext do %>
  <%= @theme.name %>
<% end %>

<div class="form-wrap card">
  <h2 class="ui center aligned icon header">
  </h2>

  <div class="ui horizontal divider">
    <i class="circular angle down icon"></i>
  </div>

  <%= render "form" %>
</div>

app/views/themes/index.html.erb
<% content_for :title do %>
  Semantic UI Themes &amp; Templates
<% end %>
<% content_for :subtext do %>
  Find the right theme for your next project
<% end %>

<% content_for :right_content do %>
  <%= link_to new_theme_path do %>
    <div class="ui circular plus icon basic button tooltip" data-content="Sell a theme" style="margin-top: 15px;">
      <i class="plus large icon"></i>
    </div>
  <% end %>
<% end %>

<% content_for :categories do %>
  <div class="ui sub secondary pointing menu">
    <%= nav_link "All", semantic_ui_themes_path %>
    <% Category.order(:name).each do |category| %>
      <%= nav_link category.name, category_path(category) %>
    <% end %>
  </div>

  <% if current_page?(admin_dashboard_path) %>
    <div class="ui message">
      <div class="header">
        <%= t(:"admin.theme_index") %>
      </div>
    </div>
  <% end %>
<% end %>

<% if @themes.any? %>
  <div class="ui two cards bottom-20">
    <%= render partial: "shared/theme", collection: @themes %>
  </div>
<% else %>
  <div style="text-align: center">
    <i class="warning circle icon massive bottom-20"></i>
    <h3 class="top-20"><%= t(:"themes.none_approved") %></h3>
    <%= link_to "Upload One Now", new_theme_path, class: "ui button massive green top-20" %>
  </div>
<% end %>

<%= will_paginate @themes %>

app/views/themes/new.html.erb
<% content_for :title do %>
  Submit a theme
<% end %>
<% content_for :subtext do %>
  and stack that cheese
<% end %>

<div class="form-wrap card">
  <h2 class="ui center aligned icon header">
    <div class="content">Here's the deal
      <p class="sub header">We like to keep things simple. Sell a theme with us and keep 70% of your sale no matter what. <%= link_to "Learn More", sell_path %></p>
    </div>
  </h2>

  <div class="ui horizontal divider">
    <i class="circular angle down icon"></i>
  </div>

  <%= render "form" %>
</div>

app/views/themes/preview.html.erb
<style type="text/css">
  * {
    margin: 0;
    padding: 0;
  }
</style>

<iframe src="<%= @theme.preview_url %>" width="100%" height="100%" frameBorder="0" seamless="seamless"></iframe>

app/views/themes/show.html.erb
<% content_for :title do %>
  <%= @theme.name %>
<% end %>
<% content_for :subtext do %>
  <div class="ui breadcrumb">
    <%= link_to "Themes", semantic_ui_themes_path, class: "section" %>
    <i class="right chevron icon divider" style="color: #fff;"></i>
    <% if @theme.categories.first %>
      <%= link_to @theme.categories.first.name, category_path(@theme.categories.first) %>
    <% end %>
    <i class="right chevron icon divider" style="color: #fff;"></i>
    <span class="section"><%= @theme.name %></span>
  </div>
<% end %>

<% content_for :right_content do %>
  <div class="ui inverted basic icon buttons" style="margin-top: 17px;">
  <%= link_to preview_theme_path(@theme), class: "ui button tooltip", data: { content: "Preview this Theme" }, target: "_blank" do %>
    <i class="expand icon"></i>
  <% end %>
    <% if current_user %>
      <% if !current_user.favorited_theme?(@theme) %>
        <%= link_to favorites_path(favorited_id: @theme.id, favorited_type: "Theme"), class: "ui button tooltip", data: {content: "Add to Favorites" }, method: :post do %>
          <i class="star icon"></i>
        <% end %>
      <% else %>
        <%= link_to favorite_path(favorited_id: @theme.id, favorited_type: "Theme"), class: "ui button tooltip", data: {content: "Remove from Favorites" }, method: :delete do %>
          <i class="star disabled icon"></i>
        <% end %>
      <% end %>
    <% else %>
      <%= link_to signin_path, class: "ui button tooltip", data: {content: "Sign in to Favorite" } do %>
        <i class="star icon"></i>
      <% end %>
    <% end %>
    <%= link_to new_theme_path, class: "ui button tooltip", data: { content: "Create a theme" } do %>
      <i class="plus icon"></i>
    <% end %>
  </div>
<% end %>


<% if !@theme.approved? %>
  <div class="ui one column grid top-20">
    <div class="column">
      <div class="ui yellow message">
        <div class="header">
          <%= t(:"admin.theme_pending") %>
        </div>
      </div>
    </div>
  </div>
<% end %>

<hr class="ui divider hidden">

<div class="ui grid">
  <div class="eleven wide column">
    <div class="ui segment image-frame">
      <%= image_tag @theme.default_image_url, :width => "100%" %>
    </div>

    <div class="item-descript">
      <h3 class="ui dividing header">Description</h3>
      <p><%= simple_format(@theme.description) %></p>
    </div>

    <% if logged_in? && current_user.can_edit_theme?(@theme) %>
      <hr class="ui divider hidden">
      <div class="ui menu action-bar">
        <%= link_to t(:"actions.edit"), edit_theme_path, class: "item" %>
        <%= link_to "Delete", theme_path(@theme), method: 'delete', :data => { confirm: t(:"actions.confirm_delete") }, class: "item" %>
      </div>
    <% end %>
  </div>

  <div class="five wide column">
    <div class="column">
      <%= link_to preview_theme_path(@theme), class: "ui huge blue icon labeled fluid button bottom-20", target: "_blank" do %>
        <i class="share icon"></i>
        live preview
      <% end %>
    </div>
    <div class="column" style="text-align: center;">
      <%= call_to_action(@theme) %>
    </div>

    <div class="ui segment">
      <header class="ui top attached label"><b>Application License</b></header>
      <div class="ui list">
        <%= link_to theme_path(@theme.id, license: "single"), class: "item" do %>
          Single
          <div class="right floated ui tag labels">
            <span class="ui label">
              <%= number_to_currency @theme.price_list.single_tier, precision: 0 %>
            </span>
          </div>
        <% end %>
        <%= link_to theme_path(@theme, license: "multiple"), class: "item" do %>
          Multiple
          <div class="right floated ui tag labels">
            <span class="ui label">
              <%= number_to_currency @theme.price_list.multiple_tier, precision: 0 %>
            </span>
          </div>
        <% end %>
        <%= link_to theme_path(@theme, license: "extended"), class: "item" do %>
          Extended
          <div class="right floated ui tag labels">
            <span class="ui label">
              <%= number_to_currency @theme.price_list.extended_tier, precision: 0 %>
            </span>
          </div>
        <% end %>
      </div>
    </div>

    <table class="ui table segment">
      <thead><tr><th colspan="2">Theme Details</th></tr></thead>
      <tbody>
        <tr>
          <td>Category</td>
          <td>
            <% @theme.categories.each do |category| %>
              <%= link_to category.name, category_path(category) %>
            <% end %>
          </td>
        </tr>
        <tr>
          <td>Compatibility</td>
          <td>
            <% @theme.browsers.each do |browser| %>
              <%= browser %><br>
            <% end %>
          </td>
        </tr>
        <tr>
          <td>Preprocessor</td>
          <td><%= @theme.preprocessor %></td>
        </tr>
        <tr>
          <td>Tags</td>
          <td><%= @theme.tags.map(&:name).reject(&:blank?).map { |t| link_to t, tag_path(t) }.join(', ').html_safe %></td>
        </tr>
        <tr>
          <td>Released</td>
          <td><%= time_ago_in_words @theme.created_at %> ago</td>
        </tr>
        <tr>
          <td>Author</td>
          <td><%= link_to @theme.owner.username, user_path(@theme.owner.user) %></td>
        </tr>
      </tbody>
    </table>
  </div>
</div>