config/routes.rb
WrapSemantic::Application.routes.draw do
  root "info#home"

  get "/sell-semantic-ui-themes", to: "info#sell", as: "sell"
  get "/logout",                  to: "sessions#destroy", as: "logout"
  get "/signin",                  to: "sessions#new",     as: "signin"
  get "/privacy-policy",          to: "info#privacy_policy"
  get "/terms",                   to: "info#terms"
  get "/faq",                     to: "info#faq"
  get "/about",                   to: "info#about"

  ["semantic-ui-themes", "semantic-ui-snippets"].each do |slug|
    controller = slug.gsub("semantic-ui-", "")
    get "/#{slug}", to: "#{controller}#index"
  end

  resource  :account,             only: [:show]
  resources :categories
  resource  :dashboard,           only: [:show]
  resources :downloads,           only: [:create]
  resources :expos,               except: [:show]

  resources :favorites,           only: [:create, :destroy]

  resources :payment_preferences, only: [:new, :create]
  resources :previews,            only: [:show]
  resources :sessions,            only: [:new, :create]
  resources :snippets do
    member do
      get 'iframe_content'
    end
  end
  resources :subscriptions,       only: [:create]

  resources :tags,                only: [:show]
  resources :themes, defaults: { format: "html" } do
    member do
      get 'preview'
    end
  end

  resources :theme_approvals,     only: [:update, :destroy]
  resources :expo_approvals,      only: [:update, :destroy]
  resources :users

  namespace :admin do
    resource :dashboard,          only: [:show]
  end
end

app/views/shared/_footer.html.erb
<div class="ui vertical inverted black footer segment">
  <div class="container">
    <div class="ui stackable inverted divided relaxed grid">
      <div class="three wide column">
        <h5 class="ui blue inverted header">Themes</h5>
        <div class="ui inverted link list">
          <%= link_to "View all Themes", semantic_ui_themes_path, class: "item" %>
          <%= link_to "Sell a Theme", new_theme_path, class: "item" %>
          <%= link_to "How it Works", sell_path, class: "item" %>
        </div>
      </div>
      <div class="three wide column">
        <h5 class="ui orange inverted header">Snippets</h5>
        <div class="ui inverted link list">
          <%= link_to "View Snippets", snippets_path, class: "item" %>
          <%= link_to "Create a Snippet", new_snippet_path, class: "item" %>
        </div>
      </div>
      <div class="three wide column">
        <h5 class="ui green inverted header">Expo</h5>
        <div class="ui inverted link list">
          <%= link_to "Built with Semantic", expos_path, class: "item" %>
          <%= link_to "Submit a Site", new_expo_path, class: "item" %>
          <%= link_to "FAQ", faq_path, class: "item" %>
        </div>
      </div>
      <div class="six wide column">
        <h3 class="ui inverted header">Semantic Kit</h3>
        <p></p>
        <p>made with <i class="heart icon"></i> in dc &amp; nyc.</p>
        <p class="terms-privacy">&copy; <%= Time.now.year %> |
          <%= link_to "About", about_path, class: "terms-privacy" %> |
          <%= link_to "Privacy", privacy_policy_path, class: "terms-privacy" %> |
          <%= link_to "Terms", terms_path, class: "terms-privacy" %>
        </p>
      </div>
    </div>
  </div>
</div>
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-28250229-11', 'auto');
  ga('send', 'pageview');

</script>

app/views/shared/_nav.html.erb
<div class="ui tiered nav menu">
  <div class="container">
    <%= link_to root_path, :class => 'item logo' do %>
      <b>Semantic</b> Kit
    <% end %>
    <%= link_to "Themes", semantic_ui_themes_path, class: "item" %>
    <%= link_to "Snippets", semantic_ui_snippets_path, class: "item" %>
    <div class="ui dropdown item">
      <a href="#">Expo</a>
      <div class="menu">
        <%= link_to "View Gallery", expos_path, class: "item" %>
        <%= link_to "Submit a Site", new_expo_path, class: "item" %>
      </div>
    </div>
    <div class="right menu">
      <% if current_user %>
        <div class="ui dropdown item">
          <%= current_user.username %><i class="icon dropdown"></i>
          <div class="menu">
            <%= link_to user_path(current_user.username), class: "item" do %>
              <i class="browser icon"></i>Profile</a>
            <% end %>
            <%= link_to dashboard_path, class: "item" do %>
              <i class="settings icon"></i>Dashboard
            <% end %>
            <%= link_to logout_path, class: "item" do %>
              <i class="sign out icon"></i>Log out
            <% end %>
            <% if current_user && current_user.admin? %>
              <%= link_to "Admin Dashboard", admin_dashboard_path, class: "item" %>
              <%= link_to "All Users", users_path, class: "item" %>
            <% end %>
          </div>
        </div>
      <% else %>
        <div class="ui item"><%= link_to "Sign In", signin_path %></div>
        <div class="ui item"><%= link_to "Sign Up", new_user_path %></div>
      <% end %>
    </div>
  </div>
</div>

app/views/shared/_subnav.html.erb
<div class="subheader">
  <div class="container">
    <div class="right-content">
      <%= yield :right_content %>
    </div>

    <h2 class="ui header inverted">
      <%= yield :title %>
      <div class="sub header">
        <%= yield :subtext %>
      </div>
    </h2>
  </div>
</div>

app/views/shared/_theme.html.erb
<div class="ui card top-20">
  <%= link_to theme_path(theme), class: "image" do %>
    <%= image_tag theme.default_image_url %>
  <% end %>
  <div class="content">
    <span class="ui right floated icon price-point">
      <%= number_to_currency(theme.price_list.single_tier, precision: 0) %>
    </span>
    <%= link_to theme.name, theme_path(theme), class: "header" %>
    <div class="meta">
      <span class="time">Released <%= time_ago_in_words(theme.created_at) %> ago</span>
    </div>
  </div>
</div>