config/routes.rb
WrapSemantic::Application.routes.draw do
  root "info#home"

  get "/sell-semantic-ui-themes", to: "info#sell", as: "sell"
  get "/logout",                  to: "sessions#destroy", as: "logout"
  get "/signin",                  to: "sessions#new",     as: "signin"
  get "/privacy-policy",          to: "info#privacy_policy"
  get "/terms",                   to: "info#terms"
  get "/faq",                     to: "info#faq"
  get "/about",                   to: "info#about"

  ["semantic-ui-themes", "semantic-ui-snippets"].each do |slug|
    controller = slug.gsub("semantic-ui-", "")
    get "/#{slug}", to: "#{controller}#index"
  end

  resource  :account,             only: [:show]
  resources :categories
  resource  :dashboard,           only: [:show]
  resources :downloads,           only: [:create]
  resources :expos,               except: [:show]

  resources :favorites,           only: [:create, :destroy]

  resources :payment_preferences, only: [:new, :create]
  resources :previews,            only: [:show]
  resources :sessions,            only: [:new, :create]
  resources :snippets do
    member do
      get 'iframe_content'
    end
  end
  resources :subscriptions,       only: [:create]

  resources :tags,                only: [:show]
  resources :themes, defaults: { format: "html" } do
    member do
      get 'preview'
    end
  end

  resources :theme_approvals,     only: [:update, :destroy]
  resources :expo_approvals,      only: [:update, :destroy]
  resources :users

  namespace :admin do
    resource :dashboard,          only: [:show]
  end
end

app/controllers/admin/dashboards_controller.rb
class Admin::DashboardsController < ApplicationController

  def show
    redirect_to semantic_ui_themes_path unless current_user && current_user.admin?

    @themes = Theme.pending
    @expos  = Expo.pending
  end
end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController
  before_filter :authenticate

  def show
    @themes = current_user.themes
    @snippets = current_user.snippets
  end
end

app/helpers/dashboards_helper.rb
module DashboardsHelper
  def revenue_explanation_for(theme)
    "(#{number_to_currency(theme.gross_sales)} x #{(PriceList::THEME_CREATOR_PERCENTAGE * 100)}%)"
  end

  def formatted_sales_by_price_for(theme)
    theme.sales_tracker.sales_grouped_by_price.map{|k,v| "#{number_to_currency(k)} (#{v})"}.join(", ")
  end
end

app/views/dashboards/show.html.erb
<% content_for :title do %>
  Your Dashboard
<% end %>
<% content_for :subtext do %>
  See how your Themes and Snippets are doing
<% end %>


<h1>Themes</h1>
<% if @themes.any? %>
  <table class="ui table">
    <thead>
      <tr>
        <th>Name</th>
        <th>Tier 1 Sold</th>
        <th>Tier 2 Sold</th>
        <th>Tier 3 Sold</th>
        <th>Sold By Price</th>
        <th>Total Revenue</th>
        <th>Favorites</th>
      </tr>
    </thead>
    <tbody>
      <% @themes.each do |theme| %>
        <tr>
          <td><%= link_to theme.name, theme_path(theme) %></td>
          <td><%= theme.single_tier_count %></td>
          <td><%= theme.multiple_tier_count %></td>
          <td><%= theme.extended_tier_count %></td>
          <td><%= formatted_sales_by_price_for(theme) %></td>
          <td><%= number_to_currency(theme.revenue) %> <span class="theme revenue-explanation"><%= revenue_explanation_for(theme) %><span></td>
          <td><%= theme.favorites.count %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% else %>
  <p>You haven't made any themes yet. <%= link_to "Create one here.", new_theme_path %></p>
<% end %>

<h2>Snippets</h2>
<% if @snippets.any? %>
    <table class="ui table">
    <thead>
      <tr>
        <th>Title</th>
        <th>Favorites</th>
      </tr>
    </thead>
    <tbody>
      <% @snippets.each do |snippet| %>
        <tr>
          <td><%= link_to snippet.title, snippet_path(snippet) %></td>
          <td><%= snippet.favorites.count %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% else %>
  <p>You haven't made any snippets yet. <%= link_to "Create one here.", new_snippet_path %></p>
<% end %>