config/routes.rb
WrapSemantic::Application.routes.draw do
  root "info#home"

  get "/sell-semantic-ui-themes", to: "info#sell", as: "sell"
  get "/logout",                  to: "sessions#destroy", as: "logout"
  get "/signin",                  to: "sessions#new",     as: "signin"
  get "/privacy-policy",          to: "info#privacy_policy"
  get "/terms",                   to: "info#terms"
  get "/faq",                     to: "info#faq"
  get "/about",                   to: "info#about"

  ["semantic-ui-themes", "semantic-ui-snippets"].each do |slug|
    controller = slug.gsub("semantic-ui-", "")
    get "/#{slug}", to: "#{controller}#index"
  end

  resource  :account,             only: [:show]
  resources :categories
  resource  :dashboard,           only: [:show]
  resources :downloads,           only: [:create]
  resources :expos,               except: [:show]

  resources :favorites,           only: [:create, :destroy]

  resources :payment_preferences, only: [:new, :create]
  resources :previews,            only: [:show]
  resources :sessions,            only: [:new, :create]
  resources :snippets do
    member do
      get 'iframe_content'
    end
  end
  resources :subscriptions,       only: [:create]

  resources :tags,                only: [:show]
  resources :themes, defaults: { format: "html" } do
    member do
      get 'preview'
    end
  end

  resources :theme_approvals,     only: [:update, :destroy]
  resources :expo_approvals,      only: [:update, :destroy]
  resources :users

  namespace :admin do
    resource :dashboard,          only: [:show]
  end
end

app/controllers/admin/dashboards_controller.rb
class Admin::DashboardsController < ApplicationController

  def show
    redirect_to semantic_ui_themes_path unless current_user && current_user.admin?

    @themes = Theme.pending
    @expos  = Expo.pending
  end
end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController
  before_filter :authenticate

  def show
    @themes = current_user.themes
    @snippets = current_user.snippets
  end
end

app/helpers/dashboards_helper.rb
module DashboardsHelper
  def revenue_explanation_for(theme)
    "(#{number_to_currency(theme.gross_sales)} x #{(PriceList::THEME_CREATOR_PERCENTAGE * 100)}%)"
  end

  def formatted_sales_by_price_for(theme)
    theme.sales_tracker.sales_grouped_by_price.map{|k,v| "#{number_to_currency(k)} (#{v})"}.join(", ")
  end
end

app/views/admin/dashboards/_expo.html.erb
<tr>
  <td><%= link_to expo.url, expo.url, target: "_blank" %></td>
  <td><%= link_to expo.user.username, user_path(expo.user) %></td>
  <td><%= expo.status %> - <%= link_to "Edit", edit_expo_path(expo) %></td>
  <td><%= expo.created_at.strftime("%m/%d/%Y") %></td>
  <% if expo.approved? %>
    <td></td>
  <% else %>
    <td>
      <%= button_to expo_approval_path(expo), class: "ui tiny blue labeled icon fluid button", method: :put do %>
        Approve
        <i class="checkmark icon"></i>
      <% end %>
    </td>
  <% end %>
</tr>

app/views/admin/dashboards/_theme.html.erb
<tr>
  <td><%= link_to theme.name, theme_path(theme) %></td>
  <td><%= link_to theme.owner.username, user_path(theme.owner.user) %></td>
  <td><%= theme.status %></td>
  <td><%= theme.created_at.strftime("%m/%d/%Y") %></td>
  <!-- <td><%#= theme.has_required_elements? %></td> -->
  <% if theme.approved? %>
    <td></td>
  <% elsif !theme.approved? %>
    <td>
      <%= button_to theme_approval_path(theme), class: "ui tiny blue labeled icon fluid button", method: :put do %>
        Approve
        <i class="checkmark icon"></i>
      <% end %>
    </td>
  <% end %>
</tr>

app/views/admin/dashboards/show.html.erb
<% content_for :title do %>
  <%= "Hi, #{current_user.username}!" %>
<% end %>
<% content_for :subtext do %>
  Get your Admin on
<% end %>

<% if @themes %>
  <h2>Themes</h2>
  <table class="ui table">
    <thead>
      <tr>
        <th>Name</th>
        <th>Author</th>
        <th>Status</th>
        <th>Submitted on</th>
        <!-- <th>Meets Criteria</th> -->
        <th>Action</th>
      </tr>
    </thead>
    <tbody>
      <%= render partial: "admin/dashboards/theme", collection: @themes %>
    </tbody>
  </table>
<% end %>

<% if @expos %>
  <h2>Expo Submissions</h2>
  <table class="ui table">
    <thead>
      <tr>
        <th>Name</th>
        <th>Submitted by</th>
        <th>Status</th>
        <th>Submitted on</th>
        <th>Action</th>
      </tr>
    </thead>
    <tbody>
      <%= render partial: "admin/dashboards/expo", collection: @expos %>
    </tbody>
  </table>
<% end %>